using CinemaTic.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.Extensions.DependencyInjection;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static Microsoft.AspNetCore.Hosting.Internal.HostingApplication;

namespace CinemaTic.Data.Configurations
{
    internal class ActorEntityConfiguration : IEntityTypeConfiguration<Actor>
    {
        private const string Directory = "../Cinema.Data.Seeder/Datasets";
        public void Configure(EntityTypeBuilder<Actor> builder)
        {
           builder.HasData(this.GetActors());
        }
        private IEnumerable<Actor> GetActors()
        {
            var actors = new List<Actor>()
            {
                new Actor( 1, new DateTime(1958, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "Tim Robbins", "timrobbins.jpg", "United States", 7m ),
                    new Actor( 2, new DateTime(1937, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Morgan Freeman", "morganfreeman.jpg", "United States", 2m ),
                    new Actor( 3, new DateTime(1945, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), "Bob Gunton", "bobgunton.jpg", "United States", 2m ),
                    new Actor( 4, new DateTime(1924, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), "Marlon Brando", "marlonbrando.jpg", "United States", 9m ),
                    new Actor( 5, new DateTime(1940, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), "Al Pacino", "alpacino.jpg", "United States", 10m ),
                    new Actor( 6, new DateTime(1940, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), "James Caan", "jamescaan.jpg", "United States", 2m ),
                    new Actor( 7, new DateTime(1943, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), "Robert De Niro", "robertdeniro.jpg", "United States", 1m ),
                    new Actor( 8, new DateTime(1931, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), "Robert Duvall", "robertduvall.jpg", "United States", 10m ),
                    new Actor( 9, new DateTime(1954, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), "John Travolta", "johntravolta.jpg", "United States", 9m ),
                    new Actor( 10, new DateTime(1970, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), "Uma Thurman", "umathurman.jpg", "United States", 2m ),
                    new Actor( 11, new DateTime(1930, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Clint Eastwood", "clinteastwood.jpg", "United States", 3m ),
                    new Actor( 12, new DateTime(1915, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), "Eli Wallach", "eliwallach.jpg", "United States", 2m ),
                    new Actor( 13, new DateTime(1925, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), "Lee Van Cleef", "leevancleef.jpg", "United States", 7m ),
                    new Actor( 14, new DateTime(1974, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), "Christian Bale", "christianbale.jpg", "United Kingdom", 9m ),
                    new Actor( 15, new DateTime(1979, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), "Heath Ledger", "heathledger.jpg", "Australia", 2m ),
                    new Actor( 16, new DateTime(1968, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), "Aaron Eckhart", "aaroneckhart.jpg", "United States", 4m ),
                    new Actor( 17, new DateTime(1905, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "Henry Fonda", "henryfonda.jpg", "United States", 7m ),
                    new Actor( 18, new DateTime(1952, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), "Liam Neeson", "liamneeson.jpg", "United States", 9m ),
                    new Actor( 19, new DateTime(1962, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), "Ralph Fiennes", "ralphfiennes.jpg", "United Kingdom", 1m ),
                    new Actor( 20, new DateTime(1943, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Ben Kingsley", "benkingsley.jpg", "United Kingdom", 7m ),
                    new Actor( 21, new DateTime(1981, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), "Elijah Wood", "elijahwood.jpg", "United States", 3m ),
                    new Actor( 22, new DateTime(1958, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), "Viggo Mortensen", "viggomortensen.jpg", "United States", 8m ),
                    new Actor( 23, new DateTime(1939, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), "Ian Mckellen", "ianmckellen.jpg", "United Kingdom", 6m ),
                    new Actor( 24, new DateTime(1963, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), "Brad Pitt", "bradpitt.jpg", "United States", 2m ),
                    new Actor( 25, new DateTime(1969, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), "Edward Norton", "edwardnorton.jpg", "United States", 9m ),
                    new Actor( 26, new DateTime(1951, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), "Mark Hamill", "markhamill.jpg", "United States", 10m ),
                    new Actor( 27, new DateTime(1942, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), "Harrison Ford", "harrisonford.jpg", "United States", 3m ),
                    new Actor( 28, new DateTime(1956, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), "Carrie Fisher", "carriefisher.jpg", "United States", 9m ),
                    new Actor( 29, new DateTime(1977, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), "Orlando Bloom", "orlandobloom.jpg", "United Kingdom", 6m ),
                    new Actor( 30, new DateTime(1937, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), "Jack Nicholson", "jacknicholson.jpg", "United States", 7m ),
                    new Actor( 31, new DateTime(1934, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), "Louise Fletcher", "louisefletcher.jpg", "United States", 2m ),
                    new Actor( 32, new DateTime(1974, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), "Leonardo DiCaprio", "LeonardoDiCaprio.jpg", "United States", 6m ),
                    new Actor( 33, new DateTime(1981, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), "Joseph Gordon-levitt", "josephgordon-levitt.jpg", "United States", 2m ),
                    new Actor( 34, new DateTime(1954, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), "Ray Liotta", "rayliotta.jpg", "United States", 7m ),
                    new Actor( 35, new DateTime(1943, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), "Joe Pesci", "joepesci.jpg", "United States", 10m ),
                    new Actor( 36, new DateTime(1956, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), "Tom Hanks", "tomhanks.jpg", "United States", 6m ),
                    new Actor( 37, new DateTime(1966, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), "Robin Wright", "robinwright.jpg", "United States", 8m ),
                    new Actor( 38, new DateTime(1955, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), "Gary Sinise", "garysinise.jpg", "United States", 8m ),
                    new Actor( 39, new DateTime(1964, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), "Keanu Reeves", "keanureeves.jpg", "Canada", 8m ),
                    new Actor( 40, new DateTime(1961, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), "Laurence Fishburne", "laurencefishburne.jpg", "United States", 1m ),
                    new Actor( 41, new DateTime(1967, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), "Carrie-anne Moss", "carrie-annemoss.jpg", "Canada", 3m ),
                    new Actor( 42, new DateTime(1959, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), "Kevin Spacey", "kevinspacey.jpg", "United States", 6m ),
                     new Actor( 43, new DateTime(1962, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), "Jodie Foster", "jodiefoster.jpg", "United States", 2m ),
                    new Actor( 44, new DateTime(1937, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Anthony Hopkins", "anthonyhopkins.jpg", "United States", 4m ),
                    new Actor( 45, new DateTime(1921, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), "Charles Bronson", "charlesbronson.jpg", "United States", 7m ),
                    new Actor( 46, new DateTime(1938, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), "Claudia Cardinale", "claudiacardinale.jpg", "Italy", 1m ),
                    new Actor( 47, new DateTime(1899, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), "Humphrey Bogart", "humphreybogart.jpg", "United States", 10m ),
                    new Actor( 48, new DateTime(1915, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), "Ingrid Bergman", "ingridbergman.jpg", "Sweden", 8m ),
                    new Actor( 49, new DateTime(1950, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), "Gabriel Byrne", "gabrielbyrne.jpg", "Ireland", 3m ),
                    new Actor( 50, new DateTime(1952, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), "Chazz Palminteri", "chazzpalminteri.jpg", "United States", 3m ),
                    new Actor( 51, new DateTime(1951, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), "Karen Allen", "karenallen.jpg", "United States", 1m ),
                    new Actor( 52, new DateTime(1908, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), "James Stewart", "jamesstewart.jpg", "United States", 5m ),
                    new Actor( 53, new DateTime(1929, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), "Grace Kelly", "gracekelly.jpg", "United States", 9m ),
                    new Actor( 54, new DateTime(1921, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), "Donna Reed", "donnareed.jpg", "United States", 7m ),
                    new Actor( 55, new DateTime(1878, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), "Lionel Barrymore", "lionelbarrymore.jpg", "United States", 1m ),
                    new Actor( 56, new DateTime(1932, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), "Anthony Perkins", "anthonyperkins.jpg", "United States", 1m ),
                    new Actor( 57, new DateTime(1927, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), "Janet Leigh", "janetleigh.jpg", "United States", 4m ),
                    new Actor( 58, new DateTime(1930, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), "Vera Miles", "veramiles.jpg", "United States", 10m ),
                    new Actor( 59, new DateTime(1948, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), "Jean Reno", "jeanreno.jpg", "France", 6m ),
                    new Actor( 60, new DateTime(1958, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), "Gary Oldman", "garyoldman.jpg", "United Kingdom", 4m ),
                    new Actor( 61, new DateTime(1981, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), "Natalie Portman", "natalieportman.jpg", "Israel", 10m ),
                    new Actor( 62, new DateTime(1918, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), "William Holden", "williamholden.jpg", "United States", 2m ),
                    new Actor( 63, new DateTime(1977, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), "Edward Furlong", "edwardfurlong.jpg", "United States", 5m ),
                    new Actor( 64, new DateTime(1951, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), "Beverly D'angelo", "beverlyd'angelo.jpg", "United States", 8m ),
                    new Actor( 65, new DateTime(1940, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), "Martin Sheen", "martinsheen.jpg", "United States", 1m ),
                    new Actor( 66, new DateTime(1947, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), "Arnold Schwarzenegger", "arnoldschwarzenegger.jpg", "United States", 2m ),
                    new Actor( 67, new DateTime(1956, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), "Linda Hamilton", "lindahamilton.jpg", "United States", 1m ),
                    new Actor( 68, new DateTime(1970, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), "Matt Damon", "mattdamon.jpg", "United States", 8m ),
                    new Actor( 69, new DateTime(1961, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), "Tom Sizemore", "tomsizemore.jpg", "United States", 8m ),
                    new Actor( 70, new DateTime(1967, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), "Guy Pearce", "guypearce.jpg", "Australia", 4m ),
                    new Actor( 71, new DateTime(1951, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), "Joe Pantoliano", "joepantoliano.jpg", "United States", 4m ),
                    new Actor( 72, new DateTime(1925, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), "Peter Sellers", "petersellers.jpg", "United Kingdom", 3m ),
                    new Actor( 73, new DateTime(1927, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), "George C. Scott", "georgec.scott.jpg", "United States", 9m ),
                    new Actor( 74, new DateTime(1949, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), "Sigourney Weaver", "sigourneyweaver.jpg", "United States", 3m ),
                    new Actor( 75, new DateTime(1933, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), "Tom Skerritt", "tomskerritt.jpg", "United States", 8m ),
                    new Actor( 76, new DateTime(1940, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), "John Hurt", "johnhurt.jpg", "United Kingdom", 6m ),
                    new Actor( 77, new DateTime(1990, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), "Daveigh Chase", "daveighchase.jpg", "United States", 7m ),
                    new Actor( 78, new DateTime(1937, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Suzanne Pleshette", "suzannepleshette.jpg", "United States", 10m ),
                    new Actor( 79, new DateTime(1904, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), "Cary Grant", "carygrant.jpg", "United States", 8m ),
                    new Actor( 80, new DateTime(1924, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), "Eva Marie Saint", "evamariesaint.jpg", "United States", 6m ),
                    new Actor( 81, new DateTime(1961, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), "Michael J. Fox", "michaelj.fox.jpg", "United States", 9m ),
                    new Actor( 82, new DateTime(1960, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), "Christopher Lloyd", "christopherlloyd.jpg", "United States", 1m ),
                    new Actor( 83, new DateTime(1961, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Lea Thompson", "leathompson.jpg", "United States", 4m ),
                    new Actor( 84, new DateTime(1952, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), "Roberto Benigni", "robertobenigni.jpg", "Italy", 10m ),
                    new Actor( 85, new DateTime(1949, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), "Shelley Duvall", "shelleyduvall.jpg", "United States", 3m ),
                    new Actor( 86, new DateTime(1973, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Danny Lloyd", "dannylloyd.jpg", "United States", 4m ),
                    new Actor( 87, new DateTime(1973, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), "Adrien Brody", "adrienbrody.jpg", "United States", 7m ),
                    new Actor( 88, new DateTime(1962, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), "Thomas Kretschmann", "thomaskretschmann.jpg", "Germany", 10m ),
                    new Actor( 89, new DateTime(1915, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), "Orson Welles", "orsonwelles.jpg", "United States", 1m ),
                    new Actor( 90, new DateTime(1916, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), "Kirk Douglas", "kirkdouglas.jpg", "United States", 5m ),
                    new Actor( 91, new DateTime(1933, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), "Kim Novak", "kimnovak.jpg", "United States", 5m ),
                    new Actor( 92, new DateTime(1967, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), "Jamie Foxx", "jamiefoxx.jpg", "United States", 6m ),
                    new Actor( 93, new DateTime(1956, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), "Christoph Waltz", "christophwaltz.jpg", "Germany", 6m ),
                    new Actor( 94, new DateTime(1908, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), "Fred Macmurray", "fredmacmurray.jpg", "United States", 9m ),
                    new Actor( 95, new DateTime(1907, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "Barbara Stanwyck", "barbarastanwyck.jpg", "United States", 8m ),
                    new Actor( 96, new DateTime(1893, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), "Edward G. Robinson", "edwardg.robinson.jpg", "United States", 6m ),
                    new Actor( 97, new DateTime(1977, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), "Tom Hardy", "tomhardy.jpg", "United Kingdom", 2m ),
                    new Actor( 98, new DateTime(1982, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), "Anne Hathaway", "annehathaway.jpg", "United States", 9m ),
                    new Actor( 99, new DateTime(1956, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Michael Biehn", "michaelbiehn.jpg", "United States", 1m ),
                    new Actor( 100, new DateTime(1950, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), "Cybill Shepherd", "cybillshepherd.jpg", "United States", 3m ),
                    new Actor( 101, new DateTime(1958, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), "Annette Bening", "annettebening.jpg", "United States", 8m ),
                    new Actor( 102, new DateTime(1982, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), "Thora Birch", "thorabirch.jpg", "United States", 3m ),
                    new Actor( 103, new DateTime(1957, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), "Michael Clarke Duncan", "michaelclarkeduncan.jpg", "United States", 2m ),
                    new Actor( 104, new DateTime(1953, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), "David Morse", "davidmorse.jpg", "United States", 1m ),
                    new Actor( 105, new DateTime(1964, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), "Russell Crowe", "russellcrowe.jpg", "New Zealand", 1m ),
                    new Actor( 106, new DateTime(1974, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), "Joaquin Phoenix", "joaquinphoenix.jpg", "United States", 2m ),
                    new Actor( 107, new DateTime(1965, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), "Connie Nielsen", "connienielsen.jpg", "Denmark", 7m ),
                    new Actor( 108, new DateTime(1962, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), "Jeff Garlin", "jeffgarlin.jpg", "United States", 3m ),
                    new Actor( 109, new DateTime(1953, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), "Tim Allen", "timallen.jpg", "United States", 5m ),
                    new Actor( 110, new DateTime(1962, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), "Joan Cusack", "joancusack.jpg", "United States", 6m ),
                    new Actor( 111, new DateTime(1968, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), "Hugh Jackman", "hughjackman.jpg", "Australia", 3m ),
                    new Actor( 112, new DateTime(1984, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), "Scarlett Johansson", "scarlettjohansson.jpg", "United States", 1m ),
                    new Actor( 113, new DateTime(1943, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), "Malcolm Mcdowell", "malcolmmcdowell.jpg", "United Kingdom", 1m ),
                    new Actor( 114, new DateTime(1932, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), "Peter O'toole", "petero'toole.jpg", "Ireland", 8m ),
                    new Actor( 115, new DateTime(1914, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), "Alec Guinness", "alecguinness.jpg", "United Kingdom", 7m ),
                    new Actor( 116, new DateTime(1915, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), "Anthony Quinn", "anthonyquinn.jpg", "United States", 10m ),
                    new Actor( 117, new DateTime(1976, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), "Audrey Tautou", "audreytautou.jpg", "France", 7m ),
                    new Actor( 118, new DateTime(1973, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), "Rufus Wainwright", "rufuswainwright.jpg", "United States", 1m ),
                    new Actor( 119, new DateTime(1967, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), "Rufus Sewell", "rufussewell.jpg", "United Kingdom", 8m ),
                    new Actor( 120, new DateTime(1916, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), "Gregory Peck", "gregorypeck.jpg", "United States", 2m ),
                    new Actor( 121, new DateTime(1939, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), "Harvey Keitel", "harveykeitel.jpg", "United States", 2m ),
                    new Actor( 122, new DateTime(1961, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), "Tim Roth", "timroth.jpg", "United Kingdom", 6m ),
                    new Actor( 123, new DateTime(1958, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), "Michael Madsen", "michaelmadsen.jpg", "United States", 9m ),
                    new Actor( 124, new DateTime(1962, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), "Matthew Broderick", "matthewbroderick.jpg", "United States", 5m ),
                    new Actor( 125, new DateTime(1948, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), "Jeremy Irons", "jeremyirons.jpg", "United Kingdom", 6m ),
                    new Actor( 126, new DateTime(1931, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), "James Earl Jones", "jamesearljones.jpg", "United States", 10m ),
                    new Actor( 127, new DateTime(1947, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), "James Woods", "jameswoods.jpg", "United States", 2m ),
                    new Actor( 128, new DateTime(1961, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), "Elizabeth Mcgovern", "elizabethmcgovern.jpg", "United States", 6m ),
                    new Actor( 129, new DateTime(1932, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), "Ellen Burstyn", "ellenburstyn.jpg", "United States", 3m ),
                    new Actor( 130, new DateTime(1971, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), "Jared Leto", "jaredleto.jpg", "United States", 5m ),
                    new Actor( 131, new DateTime(1970, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), "Jennifer Connelly", "jenniferconnelly.jpg", "United States", 6m ),
                    new Actor( 132, new DateTime(1962, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), "Jim Carrey", "jimcarrey.jpg", "Canada", 6m ),
                    new Actor( 133, new DateTime(1975, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), "Kate Winslet", "katewinslet.jpg", "United Kingdom", 3m ),
                    new Actor( 134, new DateTime(1948, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), "Tom Wilkinson", "tomwilkinson.jpg", "United Kingdom", 10m ),
                    new Actor( 135, new DateTime(1959, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), "Matthew Modine", "matthewmodine.jpg", "United States", 6m ),
                    new Actor( 136, new DateTime(1944, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), "R. Lee Ermey", "r.leeermey.jpg", "United States", 5m ),
                    new Actor( 137, new DateTime(1959, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), "Vincent D'Onofrio", "VincentD'Onofrio.jpg", "United States", 8m ),
                    new Actor( 138, new DateTime(1956, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), "Mel Gibson", "melgibson.jpg", "United States", 4m ),
                    new Actor( 139, new DateTime(1966, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), "Sophie Marceau", "sophiemarceau.jpg", "France", 8m ),
                    new Actor( 140, new DateTime(1941, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), "Faye Dunaway", "fayedunaway.jpg", "United States", 10m ),
                    new Actor( 141, new DateTime(1912, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), "Gene Kelly", "genekelly.jpg", "United States", 1m ),
                    new Actor( 142, new DateTime(1939, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), "John Cleese", "johncleese.jpg", "United Kingdom", 2m ),
                    new Actor( 143, new DateTime(1943, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), "Eric Idle", "ericidle.jpg", "United Kingdom", 3m ),
                    new Actor( 144, new DateTime(1926, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Marilyn Monroe", "marilynmonroe.jpg", "United States", 9m ),
                    new Actor( 145, new DateTime(1925, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), "Tony Curtis", "tonycurtis.jpg", "United States", 1m ),
                    new Actor( 146, new DateTime(1925, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), "Jack Lemmon", "jacklemmon.jpg", "United States", 3m ),
                    new Actor( 147, new DateTime(1939, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), "F. Murray Abraham", "f.murrayabraham.jpg", "United States", 1m ),
                    new Actor( 148, new DateTime(1953, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), "Tom Hulce", "tomhulce.jpg", "United States", 3m ),
                    new Actor( 149, new DateTime(1937, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), "Gary Lockwood", "garylockwood.jpg", "United States", 7m ),
                    new Actor( 150, new DateTime(1908, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), "Bette Davis", "bettedavis.jpg", "United States", 2m ),
                    new Actor( 151, new DateTime(1959, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), "Tyrone Power, Jr.", "tyronepower,jr..jpg", "United States", 9m ),
                    new Actor( 152, new DateTime(1901, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), "Marlene Dietrich", "marlenedietrich.jpg", "United States", 2m ),
                    new Actor( 153, new DateTime(1925, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), "Paul Newman", "paulnewman.jpg", "United States", 4m ),
                    new Actor( 154, new DateTime(1937, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), "Robert Redford", "robertredford.jpg", "United States", 4m ),
                    new Actor( 155, new DateTime(1934, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), "Shirley Maclaine", "shirleymaclaine.jpg", "United States", 8m ),
                    new Actor( 156, new DateTime(1930, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), "Sean Connery", "seanconnery.jpg", "United Kingdom", 10m ),
                    new Actor( 157, new DateTime(1966, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), "Alison Doody", "alisondoody.jpg", "Ireland", 3m )
            };
            return actors;
        }
    }
}
