using Cinema.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Cinema.Data.Configurations
{
    public class SectorsEntityConfiguration : IEntityTypeConfiguration<Sector>
    {
        public void Configure(EntityTypeBuilder<Sector> builder)
        {
           builder.HasData(this.GetSectors());
        }
        private IEnumerable<Sector> GetSectors()
        {
            var cinemas = new List<Data.Models.Cinema>()
            {
                 new Data.Models.Cinema( 1, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Experience the magic of movies under the stars at Starlight Cinemas! Our open-air theaters offer a unique and enchanting movie-going experience that combines the joy of cinema with the beauty of the night sky. Founded on January 15, 1985, Starlight Cinemas has been a cherished destination for families, couples, and friends seeking to create unforgettable memories. With 50 rows and 30 columns, our theaters accommodate a large audience while maintaining an intimate atmosphere. Grab your popcorn and recline in our comfortable seats as you immerse yourself in a world of cinematic wonder and twinkling constellations.", new DateTime(1985, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), "StarlightCinemas.jpg", "Starlight Cinemas", "asdasd", 30, 50, "#000000" ),
                    new Data.Models.Cinema( 2, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to Cineplex Delights, the perfect destination for delightful movies the whole family can enjoy! Established on March 5, 1999, our mission has been to bring joy, laughter, and heartwarming stories to our audiences. With 40 rows and 40 columns, our theaters provide a spacious yet cozy environment for a truly immersive cinematic experience. From the latest blockbusters to timeless classics, we curate a diverse selection of films to cater to every taste. Our friendly staff, comfortable seating, and delicious concessions ensure that your time at Cineplex Delights will be nothing short of delightful!", new DateTime(1999, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), "CineplexDelights.jpg", "Cineplex Delights", "asdasd", 40, 40, "#000000" ),
                    new Data.Models.Cinema( 3, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Step into the world of cinematic splendor at Golden Screen Theatres, where every movie shines like gold. Established on December 2, 1977, we take pride in our long-standing tradition of delivering exceptional film experiences to our patrons. With 60 rows and 45 columns, our theaters boast a grand ambiance, befitting the finest movie presentations. Our state-of-the-art facilities, crystal-clear audio, and high-definition visuals enhance your enjoyment of every film. Whether you're a film connoisseur or a casual movie-goer, Golden Screen Theatres promises to elevate your love for the silver screen to dazzling new heights.", new DateTime(1977, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), "GoldenScreenTheatres.jpg", "Golden Screen Theatres", "asdasd", 45, 60, "#000000" ),
                    new Data.Models.Cinema( 4, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Relive the golden age of cinema at Retro Rewind Cinema! Founded on October 20, 2005, our theater is a tribute to the timeless classics that continue to captivate audiences across generations. Featuring 30 rows and 60 columns, our spacious yet cozy auditoriums ensure an intimate connection with the films of yesteryears. From black-and-white masterpieces to beloved blockbusters, every screening is an immersive journey into cinematic history. Our vintage decor and classic movie posters transport you back in time as you savor the magic of the silver screen. Step into a bygone era at Retro Rewind Cinema!", new DateTime(2005, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), "RetroRewindCinema.jpg", "Retro Rewind Cinema", "asdasd", 60, 30, "#000000" ),
                    new Data.Models.Cinema( 5, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Embark on thrilling cinematic adventures at Cinematic Adventures, where every movie takes you on a journey of excitement, emotion, and wonder. Established on June 12, 2010, our theater is dedicated to curating a diverse selection of films that cater to every taste and preference. With 45 rows and 35 columns, our spacious theaters ensure maximum comfort and an enjoyable movie-going experience. Whether you're a fan of action-packed blockbusters, heartwarming dramas, or thought-provoking indies, Cinematic Adventures has something special in store for you. Let the magic of cinema sweep you away on an unforgettable adventure!", new DateTime(2010, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), "CinematicAdventures.jpg", "Cinematic Adventures", "asdasd", 35, 45, "#000000" ),
                    new Data.Models.Cinema( 6, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "At City Lights Cinemas, movies come to life and brighten up the city! Founded on July 7, 1990, our theater has been a beacon of entertainment and culture, enriching the lives of our diverse audience. With 50 rows and 30 columns, our theaters strike the perfect balance between an intimate atmosphere and a vibrant communal experience. From heartwarming romances to pulse-pounding thrillers, we curate a rich selection of films that cater to various tastes. Join us for an unforgettable evening of cinematic joy, as the city lights dance in harmony with the magic of the silver screen.", new DateTime(1990, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), "CityLightsCinemas.jpg", "City Lights Cinemas", "asdasd", 30, 50, "#000000" ),
                    new Data.Models.Cinema( 7, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to the Silver Screen Showcase, where every movie presentation is a shining gem of cinematic brilliance. Established on April 28, 1982, our theater has been a destination for film enthusiasts seeking extraordinary cinematic experiences. With 55 rows and 25 columns, our theaters offer an intimate and captivating setting for movie-goers to lose themselves in the art of storytelling. From critically acclaimed masterpieces to avant-garde works, every screening is a celebration of the finest films from around the world. Come, bask in the luminous glow of cinema at the Silver Screen Showcase!", new DateTime(1982, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), "SilverScreenShowcase.jpg", "Silver Screen Showcase", "asdasd", 25, 55, "#000000" ),
                    new Data.Models.Cinema( 8, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Experience the magic of cinematic festivals at Festival Flicks, where we celebrate the art of cinema like no other. Founded on September 8, 2003, our theater is dedicated to hosting special film festivals that showcase diverse perspectives, cultures, and genres. With 40 rows and 40 columns, our theaters offer a comfortable and inclusive space for cinephiles to immerse themselves in extraordinary storytelling. From avant-garde experimental films to heartwarming documentaries, every festival presents a unique and thought-provoking experience. Join us in our love for the silver screen and celebrate the beauty of cinema at Festival Flicks!", new DateTime(2003, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), "FestivalFlicks.jpg", "Festival Flicks", "asdasd", 40, 40, "#000000" ),
                    new Data.Models.Cinema( 9, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Embark on an otherworldly cinematic journey at Glamour Galaxy Theatres, where movies transport you to realms beyond imagination. Founded on November 19, 1995, our theater is a gateway to captivating narratives set in distant galaxies and enchanting fantasy worlds. With 60 rows and 20 columns, our theaters provide a spacious and immersive setting for grand space operas and dazzling visual effects. From mind-bending sci-fi epics to magical tales of cosmic wonder, every screening at Glamour Galaxy Theatres promises to be an unforgettable adventure through the infinite possibilities of storytelling on the silver screen.", new DateTime(1995, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), "GlamourGalaxyTheatres.jpg", "Glamour Galaxy Theatres", "asdasd", 20, 60, "#000000" ),
                    new Data.Models.Cinema( 10, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to the Majestic Movie House, where the grandeur of cinema comes to life like never before. Established on August 3, 1970, our theater is a testament to the enduring power of movies in shaping culture and inspiring hearts. With 35 rows and 50 columns, our theaters offer an intimate and inviting space to experience films in all their splendor. From epic historical dramas to mesmerizing fantasies, every screening at Majestic Movie House is a larger-than-life spectacle. Come, be enthralled by the magic of storytelling, as the curtains rise and the majesty of cinema unfolds before you.", new DateTime(1970, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), "MajesticMovieHouse.jpg", "Majestic Movie House", "asdasd", 50, 35, "#000000" ),
                    new Data.Models.Cinema( 11, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Step into Dreamland Cinemas, where your wildest dreams come to life on the silver screen. Established on May 22, 2008, our theater is dedicated to curating an extraordinary collection of films that transport you to mesmerizing realms and heartwarming tales. With 30 rows and 60 columns, our theaters offer a spacious and enchanting ambiance for a truly immersive cinematic experience. From whimsical animations to captivating fantasies, every screening at Dreamland Cinemas is a delightful journey into the realm of imagination. Unleash your inner child and embark on a magical adventure with us!", new DateTime(2008, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), "DreamlandCinemas.jpg", "Dreamland Cinemas", "asdasd", 60, 30, "#000000" ),
                    new Data.Models.Cinema( 12, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to Cinema Paradiso, a paradise for movie enthusiasts seeking a truly enchanting cinematic experience. Founded on December 12, 1988, our theater is dedicated to curating an eclectic mix of films that cater to every taste and preference. With 40 rows and 45 columns, our theaters strike the perfect balance between intimacy and grandeur, ensuring an immersive and unforgettable movie-going experience. From heartwarming romances to mind-bending mysteries, every screening at Cinema Paradiso is a celebration of the art of storytelling. Step into our cinematic paradise and let the magic of movies transport you to wondrous realms.", new DateTime(1988, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), "CinemaParadiso.jpg", "Cinema Paradiso", "asdasd", 45, 40, "#000000" ),
                    new Data.Models.Cinema( 13, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Prepare for epic cinematic journeys at Epic Adventure Theatres, where larger-than-life stories unfold before your eyes. Established on January 30, 2002, our theater is dedicated to showcasing the most awe-inspiring adventures ever captured on celluloid. With 60 rows and 25 columns, our theaters offer a spacious and immersive setting for blockbuster spectacles and heroic tales. From thrilling action sequences to breathtaking visual effects, every screening at Epic Adventure Theatres is a heart-pounding rollercoaster ride. Join us as we embark on epic quests, conquer new frontiers, and witness the triumph of the human spirit on the silver screen.", new DateTime(2002, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), "EpicAdventureTheatres.jpg", "Epic Adventure Theatres", "asdasd", 25, 60, "#000000" ),
                    new Data.Models.Cinema( 14, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to Sunset Screenings, where every movie ends with a breathtaking sunset, adding an extra touch of magic to your cinema experience. Founded on July 18, 1993, our theater is dedicated to creating unforgettable moments and heartwarming memories for our audiences. With 55 rows and 30 columns, our theaters strike the perfect balance between an intimate atmosphere and a communal sense of wonder. From romantic dramas to feel-good comedies, every screening at Sunset Screenings is a journey of emotions. Join us as we bask in the glow of cinematic brilliance and savor the beauty of sunsets on the silver screen.", new DateTime(1993, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), "SunsetScreenings.jpg", "Sunset Screenings", "asdasd", 30, 55, "#000000" ),
                    new Data.Models.Cinema( 15, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Step into the world of Classic Cinephile, where timeless classics stand the test of time and continue to captivate audiences through the ages. Established on March 7, 1965, our theater is a tribute to the artistry and brilliance of films that have shaped the course of cinematic history. With 50 rows and 30 columns, our theaters offer a comfortable and intimate setting for cinephiles to immerse themselves in the golden era of cinema. From iconic black-and-white masterpieces to beloved musicals, every screening at Classic Cinephile is a celebration of the finest storytelling in the annals of film.", new DateTime(1965, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), "ClassicCinephile.jpg", "Classic Cinephile", "asdasd", 30, 50, "#000000" ),
                    new Data.Models.Cinema( 16, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to Moonlight Movies, where enchanting movies are paired with the mesmerizing glow of moonlight, creating a magical cinematic experience like no other. Founded on October 10, 2011, our theater is dedicated to curating a diverse selection of films that cater to various tastes and preferences. With 45 rows and 35 columns, our theaters offer a cozy and intimate ambiance for a truly immersive movie-going experience. From heartwarming dramas to soul-stirring romances, every screening at Moonlight Movies is a journey of emotions. Join us as we revel in the magic of movies under the shimmering light of the moon.", new DateTime(2011, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), "MoonlightMovies.jpg", "Moonlight Movies", "asdasd", 35, 45, "#000000" ),
                    new Data.Models.Cinema( 17, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Step into the future of cinema at Vista Vision Theatres, where every movie presentation is a visionary experience. Founded on June 5, 1998, our theater is dedicated to pushing the boundaries of visual storytelling and cinematic technology. With 40 rows and 40 columns, our theaters provide a spacious and cutting-edge setting for immersive cinematic adventures. From mind-bending sci-fi epics to visually stunning animations, every screening at Vista Vision Theatres is a glimpse into the future of entertainment. Join us as we embrace innovation and witness the evolution of cinema on the silver screen.", new DateTime(1998, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), "VistaVisionTheatres.jpg", "Vista Vision Theatres", "asdasd", 40, 40, "#000000" ),
                    new Data.Models.Cinema( 18, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to Luminous Lumiere Cinema, where movies shine with the brilliance of luminescence. Founded on January 1, 1974, our theater is dedicated to curating a collection of visually stunning films that captivate your senses and ignite your imagination. With 30 rows and 50 columns, our theaters offer an intimate and captivating ambiance for movie-goers to experience the magic of light and shadow. From mesmerizing art-house creations to visually breathtaking documentaries, every screening at Luminous Lumiere Cinema is a celebration of the art of visual storytelling. Come, be dazzled by the luminous wonders of cinema.", new DateTime(1974, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), "LuminousLumiereCinema.jpg", "Luminous Lumiere Cinema", "asdasd", 50, 30, "#000000" ),
                    new Data.Models.Cinema( 19, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Enter the realm of enchantment at Magic Lantern Theatres, where movies are like magical lanterns that illuminate your imagination. Founded on November 11, 1983, our theater is dedicated to curating an extraordinary collection of films that transport you to worlds of fantasy, mystery, and wonder. With 50 rows and 35 columns, our theaters offer a spacious and immersive setting for cinematic adventures of every genre. From mystical tales to captivating animations, every screening at Magic Lantern Theatres is a journey into the extraordinary. Come, let the magic of cinema ignite your dreams and kindle the fire of imagination.", new DateTime(1983, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), "MagicLanternTheatres.jpg", "Magic Lantern Theatres", "asdasd", 35, 50, "#000000" ),
                    new Data.Models.Cinema( 20, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Escape into the realm of dreams at Dreamscape Theatres, where movies blur the lines between reality and imagination. Founded on November 8, 2007, our theater is dedicated to curating a collection of mind-bending films that challenge perceptions and inspire wonder. With 35 rows and 50 columns, our theaters provide a comfortable and immersive space for a cinematic journey through the subconscious. From surreal art-house creations to thought-provoking psychological thrillers, every screening at Dreamscape Theatres is a voyage into the depths of the human mind.", new DateTime(2007, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), "DreamscapeTheatres.jpg", "Dreamscape Theatres", "asdasd", 50, 35, "#000000" ),
                    new Data.Models.Cinema( 21, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to Cinema Royale, where every movie presentation is a royal affair. Founded on December 10, 1991, our theater exudes elegance and sophistication, creating a majestic setting for cinematic experiences fit for royalty. With 60 rows and 25 columns, our spacious theaters ensure maximum comfort and an unparalleled view of the silver screen. From regal historical dramas to opulent period pieces, every screening at Cinema Royale is a celebration of grandeur and the finest storytelling. Join us as we roll out the red carpet and immerse ourselves in the splendor of cinema.", new DateTime(1991, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), "CinemaRoyale.jpg", "Cinema Royale", "asdasd", 25, 60, "#000000" ),
                    new Data.Models.Cinema( 22, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Step into the enchanting world of the Magical Movie Garden, where every film is a blossoming experience. Founded on April 4, 2009, our theater is dedicated to curating a collection of heartwarming films that touch the soul like gentle petals. With 50 rows and 35 columns, our theaters offer a cozy and inviting ambiance for a truly magical movie-going experience. From feel-good family adventures to whimsical fairy tales, every screening at the Magical Movie Garden is a delightful journey into the realm of imagination.", new DateTime(2009, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), "MagicalMovieGarden.jpg", "Magical Movie Garden", "asdasd", 35, 50, "#000000" ),
                    new Data.Models.Cinema( 23, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Prepare to be starstruck at Starstruck Theatres, where movie stars grace the silver screen in all their glory. Founded on February 14, 1996, our theater is dedicated to showcasing blockbuster hits and the biggest names in Hollywood. With 40 rows and 40 columns, our theaters offer a glamorous and immersive setting for fans to indulge in the glitz and glam of showbiz. From red carpet premieres to action-packed adventures, every screening at Starstruck Theatres is a rendezvous with the stars.", new DateTime(1996, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), "StarstruckTheatres.jpg", "Starstruck Theatres", "asdasd", 40, 40, "#000000" ),
                    new Data.Models.Cinema( 24, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Embark on a cosmic journey at Cosmic Cinema, where movies transport you to the farthest reaches of the universe. Founded on June 25, 2013, our theater is dedicated to curating a selection of visually stunning films that celebrate the wonders of space and astronomy. With 45 rows and 35 columns, our theaters offer an immersive and awe-inspiring setting for a cinematic encounter with the cosmos. From breathtaking space documentaries to epic sci-fi sagas, every screening at Cosmic Cinema is a celestial voyage like no other.", new DateTime(2013, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), "CosmicCinema.jpg", "Cosmic Cinema", "asdasd", 35, 45, "#000000" ),
                    new Data.Models.Cinema( 25, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Discover the charm of the past at Rustic Reel Theatres, where vintage movies come to life. Founded on October 29, 1989, our theater is a nostalgic haven for cinephiles seeking the magic of classic films. With 30 rows and 60 columns, our intimate and rustic auditoriums transport you back in time to the golden era of cinema. From black-and-white masterpieces to timeless romance, every screening at Rustic Reel Theatres is a heartwarming journey to the days of old Hollywood.", new DateTime(1989, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), "RusticReelTheatres.jpg", "Rustic Reel Theatres", "asdasd", 60, 30, "#000000" ),
                    new Data.Models.Cinema( 26, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to Fantasia Flicks, where movies take you on fantastical adventures beyond your wildest dreams. Founded on September 21, 2004, our theater is dedicated to curating a collection of magical films that ignite the spark of imagination. With 55 rows and 30 columns, our theaters offer a captivating and otherworldly setting for an unforgettable cinematic experience. From mythical quests to enchanting fairy tales, every screening at Fantasia Flicks is a portal to a realm of wonder and fantasy.", new DateTime(2004, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), "FantasiaFlicks.jpg", "Fantasia Flicks", "asdasd", 30, 55, "#000000" ),
                    new Data.Models.Cinema( 27, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Step into the Renaissance era at Renaissance Cinemas, where classic art and movies converge. Founded on July 12, 1997, our theater celebrates the artistry and creativity of both Renaissance masterpieces and cinematic wonders. With 50 rows and 30 columns, our theaters offer an elegant and immersive setting for an elevated movie-going experience. From historical dramas to opulent period pieces, every screening at Renaissance Cinemas is a tribute to the timeless beauty of art and storytelling.", new DateTime(1997, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), "RenaissanceCinemas.jpg", "Renaissance Cinemas", "asdasd", 30, 50, "#000000" ),
                    new Data.Models.Cinema( 28, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to Cinema Paradigm, where movies redefine the boundaries of storytelling and imagination. Founded on December 5, 2010, our theater is dedicated to curating avant-garde films that challenge norms and push the limits of creativity. With 60 rows and 20 columns, our theaters provide a cutting-edge and thought-provoking space for cinephiles to explore new cinematic frontiers. From experimental narratives to abstract visual poetry, every screening at Cinema Paradigm is a journey into the uncharted territories of cinema.", new DateTime(2010, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), "CinemaParadigm.jpg", "Cinema Paradigm", "asdasd", 20, 60, "#000000" ),
                    new Data.Models.Cinema( 29, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Enter the realm of enchantment at Enchanted Screenings, where every movie is a spellbinding experience. Founded on August 28, 1994, our theater is dedicated to curating a collection of magical films that transport you to whimsical worlds and extraordinary adventures. With 40 rows and 45 columns, our theaters offer a cozy and immersive setting for a truly enchanting movie-going experience. From fairy tale classics to fantastical animations, every screening at Enchanted Screenings is a journey into the magic of storytelling.", new DateTime(1994, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), "EnchantedScreenings.jpg", "Enchanted Screenings", "asdasd", 45, 40, "#000000" ),
                    new Data.Models.Cinema( 30, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Prepare for thrilling adventures at Adventureplex Cinemas, where every movie is an adrenaline-pumping experience. Founded on January 17, 2001, our theater is dedicated to showcasing action-packed blockbusters and high-octane escapades. With 45 rows and 35 columns, our theaters offer a dynamic and electrifying setting for cinematic feats of daring and bravery. From pulse-pounding thrillers to heart-stopping stunts, every screening at Adventureplex Cinemas is a thrilling ride you won't forget.", new DateTime(2001, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), "AdventureplexCinemas.jpg", "Adventureplex Cinemas", "asdasd", 35, 45, "#000000" ),
                    new Data.Models.Cinema( 31, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Step into a world of vivid visions at Vivid Visions Cinema, where movies captivate your senses and immerse you in a tapestry of colors and emotions. Founded on May 13, 2012, our theater is dedicated to curating visually stunning films that celebrate the art of cinematography. With 55 rows and 30 columns, our theaters offer an intimate and mesmerizing ambiance for a truly immersive movie-going experience. From breathtaking landscapes to abstract visual poetry, every screening at Vivid Visions Cinema is a feast for the eyes and the soul.", new DateTime(2012, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), "VividVisionsCinema.jpg", "Vivid Visions Cinema", "asdasd", 30, 55, "#000000" ),
                    new Data.Models.Cinema( 32, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to Wonderscope Theatres, where every movie is a portal to magical worlds and breathtaking wonders. Founded on February 19, 2008, our theater is dedicated to curating a collection of imaginative films that spark curiosity and ignite the sense of wonder. With 30 rows and 60 columns, our theaters offer a spacious and enchanting setting for a truly captivating cinematic experience. From whimsical animations to awe-inspiring documentaries, every screening at Wonderscope Theatres is an exploration of the beauty and mysteries of our world.", new DateTime(2008, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), "WonderscopeTheatres.jpg", "Wonderscope Theatres", "asdasd", 60, 30, "#000000" ),
                    new Data.Models.Cinema( 33, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Enter the realm of Cinemagic Emporium, where movies are like magical artifacts that weave stories of enchantment and heroism. Founded on September 30, 1993, our theater is dedicated to curating a diverse selection of films that celebrate the power of storytelling. With 40 rows and 40 columns, our theaters offer a spacious and immersive setting for cinephiles to embark on extraordinary journeys. From epic quests to tales of mythical creatures, every screening at Cinemagic Emporium is a treasure trove of cinematic delights.", new DateTime(1993, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), "CinemagicEmporium.jpg", "Cinemagic Emporium", "asdasd", 40, 40, "#000000" ),
                    new Data.Models.Cinema( 34, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Prepare to be dazzled at Spectra Cinema, where movies unfold like vibrant spectrums of emotion and artistry. Founded on July 27, 1999, our theater is dedicated to curating visually stunning films that evoke a kaleidoscope of feelings. With 60 rows and 25 columns, our theaters offer a spacious and immersive setting for cinematic experiences that burst with color and vibrancy. From abstract visual poetry to breathtaking animations, every screening at Spectra Cinema is a celebration of the boundless possibilities of artistic expression.", new DateTime(1999, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), "SpectraCinema.jpg", "Spectra Cinema", "asdasd", 25, 60, "#000000" ),
                    new Data.Models.Cinema( 35, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to Sunrise Cinematech, where movies rise like the sun, illuminating the world with their brilliance. Founded on December 3, 1981, our theater is dedicated to curating a collection of cinematic masterpieces that showcase the art of filmmaking. With 55 rows and 25 columns, our theaters offer an intimate and captivating ambiance for a truly immersive movie-going experience. From critically acclaimed dramas to thought-provoking documentaries, every screening at Sunrise Cinematech is a celebration of the power of storytelling to inspire and enlighten.", new DateTime(1981, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), "SunriseCinematech.jpg", "Sunrise Cinematech", "asdasd", 25, 55, "#000000" ),
                    new Data.Models.Cinema( 36, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to CineVerse Theatres, where movies become a catalyst for thought-provoking discussions and intellectual exploration. Founded on October 6, 2005, our theater is dedicated to curating films that spark conversations and challenge perspectives. With 40 rows and 40 columns, our theaters offer an intimate and engaging setting for film enthusiasts to come together and share their cinematic experiences. From powerful dramas to mind-bending mysteries, every screening at CineVerse Theatres is an invitation to delve deeper into the art of storytelling.", new DateTime(2005, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), "CineVerseTheatres.jpg", "CineVerse Theatres", "asdasd", 40, 40, "#000000" ),
                    new Data.Models.Cinema( 37, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Embark on a cinematic journey through galaxies at Galactic Cinemaworks, where science fiction and imagination collide. Founded on July 14, 2003, our theater is dedicated to curating the best of sci-fi films that transport you to distant stars and futuristic worlds. With 50 rows and 35 columns, our theaters provide a spacious and immersive setting for thrilling space adventures and epic interstellar battles. From visionary space odysseys to thought-provoking futuristic tales, every screening at Galactic Cinemaworks is a tribute to the boundless possibilities of the cosmos.", new DateTime(2003, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), "GalacticCinemaworks.jpg", "Galactic Cinemaworks", "asdasd", 35, 50, "#000000" ),
                    new Data.Models.Cinema( 38, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Step into the realm of enchantment at Majestic Magic Theatres, where movies come to life with the wonders of illusion and wonder. Founded on January 1, 1990, our theater is dedicated to curating films that celebrate the art of magic and illusion. With 35 rows and 50 columns, our theaters offer a captivating and spellbinding setting for a truly magical cinematic experience. From dazzling magic shows to captivating fantasy adventures, every screening at Majestic Magic Theatres is a celebration of the extraordinary.", new DateTime(1990, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), "MajesticMagicTheatres.jpg", "Majestic Magic Theatres", "asdasd", 50, 35, "#000000" ),
                    new Data.Models.Cinema( 39, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to Golden Age Cinemas, a time capsule that transports you to the glorious era of classic movies. Founded on March 21, 1978, our theater is dedicated to showcasing timeless masterpieces and beloved Hollywood classics. With 55 rows and 30 columns, our theaters offer an elegant and nostalgic ambiance for cinephiles to relive the magic of cinema's golden age. From iconic movie stars to unforgettable dialogue, every screening at Golden Age Cinemas is a celebration of the timeless allure of vintage films.", new DateTime(1978, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), "GoldenAgeCinemas.jpg", "Golden Age Cinemas", "asdasd", 30, 55, "#000000" ),
                    new Data.Models.Cinema( 40, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Enter the sanctuary of cinema at CineArt Sanctuary, where movies are cherished as works of art. Founded on September 9, 2015, our theater is dedicated to curating a collection of artistic films that inspire and captivate the soul. With 30 rows and 60 columns, our theaters offer a serene and contemplative setting for a truly immersive cinematic experience. From thought-provoking dramas to visually stunning masterpieces, every screening at CineArt Sanctuary is an invitation to embrace the artistry of filmmaking.", new DateTime(2015, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), "CineArtSanctuary.jpg", "CineArt Sanctuary", "asdasd", 60, 30, "#000000" ),
                    new Data.Models.Cinema( 41, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Prepare for stellar cinematic adventures at Stellar Cinemas, where every movie shines with brilliance and spectacle. Founded on November 20, 2000, our theater is dedicated to curating blockbuster hits and visually stunning films that leave you in awe. With 60 rows and 25 columns, our theaters offer a spacious and immersive setting for larger-than-life cinematic experiences. From jaw-dropping action sequences to breathtaking visual effects, every screening at Stellar Cinemas is a cosmic journey to the stars.", new DateTime(2000, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), "StellarCinemas.jpg", "Stellar Cinemas", "asdasd", 25, 60, "#000000" ),
                    new Data.Models.Cinema( 42, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to Wanderlust Theatres, where movies take you on journeys to breathtaking destinations around the world. Founded on April 9, 2010, our theater is dedicated to curating a collection of travel films that immerse you in the wonders of different cultures and landscapes. With 45 rows and 35 columns, our theaters offer a cozy and wanderlust-inspiring setting for a truly enriching cinematic experience. From scenic documentaries to adventurous travelogues, every screening at Wanderlust Theatres is an invitation to explore the beauty of our planet.", new DateTime(2010, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), "WanderlustTheatres.jpg", "Wanderlust Theatres", "asdasd", 35, 45, "#000000" ),
                    new Data.Models.Cinema( 43, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Experience the grandeur of cinema at Grandeur Cinematech, where movies unfold with cinematic brilliance and splendor. Founded on May 18, 1986, our theater is dedicated to showcasing visually stunning films that celebrate the art of filmmaking. With 50 rows and 30 columns, our theaters offer an elegant and immersive setting for an extraordinary movie-going experience. From sweeping cinematography to breathtaking visual storytelling, every screening at Grandeur Cinematech is a celebration of the artistry and magic of movies.", new DateTime(1986, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), "GrandeurCinematech.jpg", "Grandeur Cinematech", "asdasd", 30, 50, "#000000" ),
                    new Data.Models.Cinema( 44, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to Artistic Aura Cinemas, where movies are a canvas for artistic expression and creativity. Founded on August 12, 1992, our theater is dedicated to curating films that celebrate the diverse forms of art and creativity. With 55 rows and 25 columns, our theaters offer an intimate and inspiring setting for cinephiles to revel in the beauty of artistic storytelling. From poetic narratives to abstract visual experiments, every screening at Artistic Aura Cinemas is a celebration of the myriad colors and emotions of the human experience.", new DateTime(1992, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), "ArtisticAuraCinemas.jpg", "Artistic Aura Cinemas", "asdasd", 25, 55, "#000000" ),
                    new Data.Models.Cinema( 45, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Step into the arcade of cinema at Arcade Cinemas, where every movie is a thrilling gaming experience. Founded on December 24, 2006, our theater is dedicated to curating films that blend the excitement of gaming with captivating storytelling. With 35 rows and 50 columns, our theaters offer an electrifying and immersive setting for an action-packed cinematic adventure. From virtual reality fantasies to high-stakes gaming thrillers, every screening at Arcade Cinemas is a joystick ride into the world of cinematic gaming.", new DateTime(2006, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), "ArcadeCinemas.jpg", "Arcade Cinemas", "asdasd", 50, 35, "#000000" ),
                    new Data.Models.Cinema( 46, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to CineVerse Theatres, where movies become a catalyst for thought-provoking discussions and intellectual exploration. Founded on October 6, 2005, our theater is dedicated to curating films that spark conversations and challenge perspectives. With 40 rows and 40 columns, our theaters offer an intimate and engaging setting for film enthusiasts to come together and share their cinematic experiences. From powerful dramas to mind-bending mysteries, every screening at CineVerse Theatres is an invitation to delve deeper into the art of storytelling.", new DateTime(2005, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), "CineVerseTheatres.jpg", "CineVerse Theatres", "asdasd", 40, 40, "#000000" ),
                    new Data.Models.Cinema( 47, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Embark on a cinematic journey through galaxies at Galactic Cinemaworks, where science fiction and imagination collide. Founded on July 14, 2003, our theater is dedicated to curating the best of sci-fi films that transport you to distant stars and futuristic worlds. With 50 rows and 35 columns, our theaters provide a spacious and immersive setting for thrilling space adventures and epic interstellar battles. From visionary space odysseys to thought-provoking futuristic tales, every screening at Galactic Cinemaworks is a tribute to the boundless possibilities of the cosmos.", new DateTime(2003, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), "GalacticCinemaworks.jpg", "Galactic Cinemaworks", "asdasd", 35, 50, "#000000" ),
                    new Data.Models.Cinema( 48, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Step into the realm of enchantment at Majestic Magic Theatres, where movies come to life with the wonders of illusion and wonder. Founded on January 1, 1990, our theater is dedicated to curating films that celebrate the art of magic and illusion. With 35 rows and 50 columns, our theaters offer a captivating and spellbinding setting for a truly magical cinematic experience. From dazzling magic shows to captivating fantasy adventures, every screening at Majestic Magic Theatres is a celebration of the extraordinary.", new DateTime(1990, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), "MajesticMagicTheatres.jpg", "Majestic Magic Theatres", "asdasd", 50, 35, "#000000" ),
                    new Data.Models.Cinema( 49, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Welcome to Golden Age Cinemas, a time capsule that transports you to the glorious era of classic movies. Founded on March 21, 1978, our theater is dedicated to showcasing timeless masterpieces and beloved Hollywood classics. With 55 rows and 30 columns, our theaters offer an elegant and nostalgic ambiance for cinephiles to relive the magic of cinema's golden age. From iconic movie stars to unforgettable dialogue, every screening at Golden Age Cinemas is a celebration of the timeless allure of vintage films.", new DateTime(1978, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), "GoldenAgeCinemas.jpg", "Golden Age Cinemas", "asdasd", 30, 55, "#000000" ),
                    new Data.Models.Cinema( 50, "#FF0000", 0, "#000000", "#FFFFFF", "#FFFFFF", "#000000", "Enter the sanctuary of cinema at CineArt Sanctuary, where movies are cherished as works of art. Founded on September 9, 2015, our theater is dedicated to curating a collection of artistic films that inspire and captivate the soul. With 30 rows and 60 columns, our theaters offer a serene and contemplative setting for a truly immersive cinematic experience. From thought-provoking dramas to visually stunning masterpieces, every screening at CineArt Sanctuary is an invitation to embrace the artistry of filmmaking.", new DateTime(2015, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), "CineArtSanctuary.jpg", "CineArt Sanctuary", "asdasd", 60, 30, "#000000" )
            };

            var collection = new List<Sector>();
            int c = 1;
            foreach (var cinema in cinemas)
            {
                char startLetter = 'A';

                List<Sector> sectors = new List<Sector>();
                for (int i = 1; i <= cinema.SeatRows; i += 10)
                {
                    for (int j = 1; j <= cinema.SeatCols; j += 15)
                    {
                        int endRow = i + 10 - 1;
                        int endCol = j + 15 - 1;

                        sectors.Add(new Sector
                        {
                            Id = c,
                            CinemaId = cinema.Id,
                            SectorName = startLetter.ToString(),
                            StartRow = i,
                            StartCol = j,
                            EndRow = endRow > cinema.SeatRows ? cinema.SeatRows : endRow,
                            EndCol = endCol > cinema.SeatCols ? cinema.SeatCols : endCol
                        });
                        c++;
                        startLetter++;
                    }
                }
                collection.AddRange(sectors);
            }
            return collection;
        }
    }
}
